name: hello
version: 1.0.0
description: Minimal Hello World example demonstrating basic Swiftlets
author: Swiftlets Team
type: example

swiftlets:
  - path: /
    source: src/index.swift
    
  - path: /hello
    source: src/index.swift

dependencies:
  - SwiftletsCore

build:
  platforms: [macos, linux]
  architectures: [x86_64, arm64]

metadata:
  tags: [example, beginner, hello-world]
  difficulty: beginner
  estimated_time: 5min