import Foundation

// Simple swiftlet that outputs HTTP response format
// No result builders, just plain string output

let method = ProcessInfo.processInfo.environment["REQUEST_METHOD"] ?? "GET"
let path = ProcessInfo.processInfo.environment["REQUEST_PATH"] ?? "/"
let headers = ProcessInfo.processInfo.environment["REQUEST_HEADERS"] ?? "{}"

// Read body from stdin if present
var body = ""
if let inputData = try? FileHandle.standardInput.readToEnd(),
   let inputString = String(data: inputData, encoding: .utf8) {
    body = inputString
}

// Generate HTML response
let html = """
<!DOCTYPE html>
<html>
<head>
    <title>Hello from Swiftlet</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            margin-bottom: 20px;
        }
        .info {
            background: #f0f0f0;
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
            font-family: 'Courier New', monospace;
        }
        .label {
            font-weight: bold;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 Hello from Swiftlet!</h1>
        <p>This page was generated by a standalone Swift executable.</p>
        
        <div class="info">
            <span class="label">Method:</span> \(method)
        </div>
        
        <div class="info">
            <span class="label">Path:</span> \(path)
        </div>
        
        <div class="info">
            <span class="label">Time:</span> \(Date().description)
        </div>
        
        <div class="info">
            <span class="label">Process ID:</span> \(ProcessInfo.processInfo.processIdentifier)
        </div>
        
        <h2>How it works</h2>
        <p>This swiftlet is a simple Swift executable that:</p>
        <ul>
            <li>Receives HTTP request data via environment variables</li>
            <li>Generates HTML content</li>
            <li>Outputs the response in HTTP format</li>
            <li>Is executed by the Swiftlets server for each request</li>
        </ul>
        
        <p><em>No result builders yet - just a proof of concept!</em></p>
    </div>
</body>
</html>
"""

// Output HTTP response format
print("Status: 200")
print("Content-Type: text/html; charset=utf-8")
print("X-Swiftlet: hello/index")
print("")  // Empty line between headers and body
print(html)